name: Update POT file

on:
  push:
    branches:
    - dev
    paths:
    - '**.php'
    - '**.js'

jobs:
  update-pot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update POT file
      uses: platform-coop-toolkit/action-wp-pot-generator@master
      with:
        save_path: './languages'
        item_slug: 'pressbooks-saml-sso'
        domain: 'pressbooks-saml-sso'
        package_name: 'Pressbooks SAML Single Sign-On'
        headers: "{\"Report-Msgid-Bugs-To\":\"https://github.com/pressbooks/pressbooks-saml-sso/issues\"}"
    - name: Commit updated POT file
      uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: 'chore: update languages/pressbooks-saml-sso.pot'
